services:
  - type: web
    name: go-todo-bot
    runtime: docker
    region: ohio
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GOOGLE_SCRIPT_URL
        sync: false
      - key: SENDGRID_KEY
        sync: false
      - key: ADMIN_TELEGRAM_ID
        sync: false
      - key: TEST_EMAIL
        sync: false
      - key: GO111MODULE
        value: "on"
    healthCheckPath: /healthz
    numInstances: 1 