services:
  - type: web
    name: go-todo-bot
    env: docker
    dockerfilePath: ./go-todo-bot/Dockerfile
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GOOGLE_SCRIPT_URL
        sync: false
      - key: SENDGRID_KEY
        sync: false
      - key: ADMIN_TELEGRAM_ID
        sync: false
      - key: TEST_EMAIL
        sync: false
    healthCheckPath: /healthz
    numInstances: 1
    buildCommand: cd go-todo-bot && go build -tags netgo -ldflags '-s -w' -o app ./cmd/bot
    startCommand: ./go-todo-bot/app 